### ISSUE TITLE
Lint Diff fails unexpectedly

### ISSUE THREAD

**Issue by komakkar** [Azure/azure-openapi-validator#288]
**Describe the bug**
````
{ Error: Command failed: node /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:66:25
    at step (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:52:23)
    at Object.next (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:33:53)
    at /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:23:12)
    at run (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:60:32)
    at Object.<anonymous> (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.28/private/azure-swagger-validation/azureSwaggerValidation/dist/entry.js:72:1)

````
**To Reproduce**
The PR where this happened. 
https://github.com/Azure/azure-rest-api-specs-pr/pull/7023/checks?check_run_id=6257159213
**Expected behavior**
If there is an error in swagger, it should be actionable .
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jianyexi** [comment]
@komakkar it's not a bug but a validation error you need to fix , seem 'allowEmptyValue' is not a valid swagger keyword
