### ISSUE TITLE
Some rule(s) seem to assume existence of operationId

### ISSUE THREAD

**Issue by olydis** [Azure/azure-openapi-validator#83]
see https://github.com/Azure/autorest/issues/2500

At least the `ListInOperationName` rule seems to do that, but I assume it's not the only one:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at AutoRest.Swagger.Validation.ListInOperationName.<GetValidationMessages>d__11.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at AzureValidator.<ProcessInternal>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__11.MoveNext()
```

Maybe we already have that, but: We should also have a rule that actually *complains* about missing operation ID's 🙂

**Comment by dsgouda** [comment]
Fixed with the PR.
